import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://www.linkedin.com/login');
  await page.getByRole('textbox', { name: 'Email or phone' }).click();
  await page.getByRole('textbox', { name: 'Email or phone' }).fill('paulsouraj99@gmail.com');
  await page.getByRole('textbox', { name: 'Email or phone' }).press('Tab');
  await page.getByRole('textbox', { name: 'Password' }).fill('Souraj@123');
  await page.getByRole('button', { name: 'Sign in', exact: true }).click();
  await page.goto('https://www.linkedin.com/feed/');
  await page.getByRole('button', { name: 'Jobs, 0 new notifications' }).click();
  await page.goto('https://www.linkedin.com/jobs/');
  await page.getByTestId('JobsHomeFeedModuleListCollection').getByRole('link', { name: 'Software Development Engineer' }).click();
  await page.getByRole('combobox', { name: 'Search by title, skill, or' }).click();
  await page.getByText('senior software engineer jobs').click();
  await page.getByRole('link', { name: 'Easy Apply to this job' }).click();
  await page.getByRole('button', { name: 'Continue to next step' }).click();
  await page.getByRole('button', { name: 'Review your application' }).click();
  await page.getByRole('button', { name: 'Submit application' }).click();
  await page.getByRole('button', { name: 'Done' }).click();
  await page.getByRole('button', { name: 'Senior Software Engineer- Backend (Verified job) Everbridge Bengaluru (Remote)' }).click();
  await page.getByRole('link', { name: 'Easy Apply to this job' }).click();
  await page.getByRole('button', { name: 'Continue to next step' }).click();
  await page.getByRole('button', { name: 'Continue to next step' }).click();
  await page.locator('#radio-button-form-component-formElement-urn-li-jobs-applyformcommon-easyApplyFormElement-4360393884-25449163572-multipleChoice').getByText('Yes').click();
  await page.getByRole('textbox', { name: 'If yes, who?' }).click();
  await page.locator('#radio-button-form-component-formElement-urn-li-jobs-applyformcommon-easyApplyFormElement-4360393884-25449163572-multipleChoice').getByText('No', { exact: true }).click();
  await page.locator('#radio-button-form-component-formElement-urn-li-jobs-applyformcommon-easyApplyFormElement-4360393884-25449163548-multipleChoice').getByText('No', { exact: true }).click();
  await page.getByRole('button', { name: 'Continue to next step' }).click();
  await page.getByRole('region', { name: 'Your job application progress' }).selectOption('3-5 Years');
  await page.getByRole('textbox', { name: 'What is your Current Salary ?*' }).click();
  await page.getByRole('textbox', { name: 'What is your Current Salary ?*' }).fill('18');
  await page.getByRole('textbox', { name: 'What is your Expected Salary' }).click();
  await page.getByRole('textbox', { name: 'What is your Expected Salary' }).fill('26');
  await page.getByRole('textbox', { name: 'What is your Expected Salary' }).selectOption('0-30 Days');
  await page.getByRole('textbox', { name: 'Current Location*' }).click();
  await page.getByRole('textbox', { name: 'Current Location*' }).fill('pune');
  await page.getByRole('button', { name: 'Continue to next step' }).click();
  await page.getByText('Yes').click();
  await page.getByRole('button', { name: 'Continue to next step' }).click();
  await page.getByRole('textbox', { name: 'What is your current location?' }).click();
  await page.getByRole('textbox', { name: 'What is your current location?' }).fill('pune');
  await page.getByRole('button', { name: 'Review your application' }).click();
  await page.getByRole('button', { name: 'Submit application' }).click();
  await page.getByRole('button', { name: 'Done' }).click();
});